### register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "vangiang",
    "password": "123456",
    "phone" : "0976320547"
}

### signIn
POST http://localhost:5000/api/auth/signIn
Content-Type: application/json

{
    "phone" : "0976320547",
    "password": "123456"
}

### insert data 
POST http://localhost:5000/api/insert/
Content-Type: application/json

### get categories 
GET http://localhost:5000/api/category/
Content-Type: application/json
