### register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "vangiang",
    "password": "123456",
    "phone" : "0976320547"
}

### signIn
POST http://localhost:5000/api/auth/signIn
Content-Type: application/json

{
    "phone" : "0896119779",
    "password": "123456"
}

### insert orther data 
POST http://localhost:5000/api/insert/orther
Content-Type: application/json

### insert prices and areas data
POST http://localhost:5000/api/insert/prices-areas
Content-Type: application/json

### get categories 
GET http://localhost:5000/api/category/
Content-Type: application/json

### get posts 
GET http://localhost:5000/api/post/
Content-Type: application/json

### get posts limit
GET http://localhost:5000/api/post/limit/?page=0
Content-Type: application/json

### get new posts
GET http://localhost:5000/api/post/newPost
Content-Type: application/json

### get prices
GET http://localhost:5000/api/price/
Content-Type: application/json

### get areas
GET http://localhost:5000/api/area/
Content-Type: application/json

### get province
GET http://localhost:5000/api/province/
Content-Type: application/json