const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILED: 'SIGNIN_FAILED',
    LOGOUT: 'LOGOUT',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT'
}

export default actionTypes